### ISSUE TITLE
feat(vue): implement tree-shaken icons & async import

### ISSUE THREAD

**Issue by mesqueeb** [CyCraft/pepicons#19]
- [ ] update the scripts to auto generate each Pepicon as a vue with the SVG code & support for the same props we use for `Pepicon.vue` currently
- Note: You'll have to have a look around here:
https://github.com/cycraft/pepicons/blob/1f203788dd6c045782740551ba2721b9be72cb4e/scripts/generateSvgStrings.js/#L217
- [ ] update the `Pepicon` vue file to use these async Pepicon vue files instead of the current implementation
- Note: feel free to make big architectural changes for the sake of improving / organising the codebase
- Note: feel free to convert the `.js` files in scripts to `.ts` and execute through esbuild register.

**Comment by mesqueeb** [comment]
<img width="642" alt="image" src="https://user-images.githubusercontent.com/3253920/104884193-524c2880-59a9-11eb-82c3-b936226ff241.png">

**Comment by egoist** [comment]
If tree shaking, you have to import the icon individually, like: 

```js
import { ClipboardIcon } from 'xxx'

<ClipboardIcon />
```

does this sound ok for this lib?

**Comment by mesqueeb** [comment]
@egoist 
i'm wondering if we can do it via some sort of async import...?

Eg. it would be awesome if we can use an icon just like now:
`<Pepicon name="airplane" type="pop" />`
and then internally make an async import of the svg string

**Comment by egoist** [comment]
In the meantime, it can still keep a component that allows to use every icon:

```js
// Eveything
export const PepIcon

// Individually exported
export const ClipboardIcon
```

**Comment by egoist** [comment]
Where the `PepIcon` can load each icon via `defineAsyncComponent` (async import)

**Comment by mesqueeb** [comment]
@egoist
let's keep the current api, and only implement async import for now:

```html
<Pepicon name="airplane" type="pop" />
```

will make a new ticket in the future for the other kind of treeshaking

**Comment by mesqueeb** [comment]
@egoist
After giving it some thought, I think I want prepare both methods either way:
- Tree-shaken import via eg. `import { PepiconAirplane } from '@vue/pepicons'`
- Async import for `Pepicon.vue` which fetches the icon SVG as string asynchronously

I've added both these as todos to the original post.
🙇🏻‍♂️

**Comment by egoist** [comment]
> Async import for Pepicon.vue which fetches the icon SVG as string asynchronously

Instead of fetching the SVG as string asynchronously, why not just use an async component? Like this:

`PepiconAirplane.vue`

```vue
<template><svg>...</svg></template>
```

`@pepicons/vue`

```js
import { h, defineAsyncComponent } from 'vue'

export { default as PepiconAirplane } from './icons/PepiconAirplane.vue'

export const icons = {
  airplane: defineAsyncComponent(() => import('./icons/PepiconAirplane.vue''))
}

export const Pepicon = defineComponent({
  setup({ name }) {
    return () => h(icons[name])
  }
})
```

**Comment by mesqueeb** [comment]
@egoist 
let's go with the `defineAsyncComponent`

Can you add the logic to generate this to the scripts? You'll have to have a look around here:
https://github.com/cycraft/pepicons/blob/1f203788dd6c045782740551ba2721b9be72cb4e/scripts/generateSvgStrings.js/#L217

updated the OP.
