### ISSUE TITLE
time related icons

### ISSUE THREAD

**Issue by mesqueeb** [CyCraft/pepicons#25]
### requested icon
"countdown / timer" タイマー
"stopwatch" ストップウォッチ
"alarm" アラームクロック
"hourglass / sandglass" 砂時計
"wrist-watch" 腕時計
"turn back time" 時間を戻す

**Comment by mesqueeb** [comment]
released
![image](https://user-images.githubusercontent.com/3253920/189256289-9b40f7a0-9c9c-4af6-9a66-7f6dba014575.jpeg)

**Comment by mesqueeb** [comment]
@noeldemartin check it out : ) what do you think?

**Comment by NoelDeMartin** [comment]
Those look great, thanks :D.

By the way, I'm using these icons in a recipes manager I'm working on called [Umai](https://umai.noeldemartin.com/). It's still in Beta, but I'll add the proper attributions before releasing it :).

**Comment by mesqueeb** [comment]
@NoelDeMartin that sounds great! I love your logo and branding. I like in Tokyo, so the word Umai is right on point! ;)

I wish you all the luck and success !!
