### ISSUE TITLE
fix(pepicons.com): iPhone SE tweaks

### ISSUE THREAD

**Issue by mesqueeb** [CyCraft/pepicons#27]
currently on iPhone SE:
![](https://user-images.githubusercontent.com/3253920/189257006-1450c5b5-650c-4c12-a215-181c0b697a3f.mp4)

make CSS tweaks that you feel improve the UI.

there is no design file, so try and play around with the CSS by eye until you think it looks better : )

**Comment by LovelyAndy** [comment]
Fix colorpicker and mobile input overflow

**Comment by mesqueeb** [comment]
fixed
