### ISSUE TITLE
Magnet

### ISSUE THREAD

**Issue by oxxie** [CyCraft/pepicons#30]
### requested icon

A magnet
Based on the magnet emoji 🧲 but stylized your way, and maybe with the opening at the top? I'd like to use it for my Magnetize PopClip extension. Thanks!

### category suggestion

Item

### search synonyms

magnet, magnetize, attract, attraction, repel, repulsion

**Comment by mesqueeb** [comment]
@oxxie I've added your requested Magnet icon!
Check out the website and search for Magnet!!

https://pepicons.com/?q=magnet

I hope you like it 💜

<img width="201" alt="image" src="https://user-images.githubusercontent.com/3253920/104560864-dc368180-5689-11eb-8c30-68b0a16bf647.png">

**Comment by oxxie** [comment]
Thank you very much! Will use it for my [Magnetize PopClip extension](https://github.com/pilotmoon/PopClip-Extensions/blob/master/extensions/Magnetize.popclipextz)!
