### ISSUE TITLE
clipboard check

### ISSUE THREAD

**Issue by egoist** [CyCraft/pepicons#94]
### requested icon

clipboard check, it's useful to indicate that the something is copied to clipboard

<img width="85" alt="CleanShot 2022-02-24 at 19 56 05@2x" src="https://user-images.githubusercontent.com/8784712/155519457-9bc21737-eb04-4ab6-aa45-170a22b25532.png">

### category suggestion

text

### search synonyms

clipboard

**Comment by mesqueeb** [comment]
@egoist thanks for the request!

will try to do a release within 1~2 weeks that will include this one
![](https://cdn.discordapp.com/attachments/603448477179052032/947185782056177754/unknown.png)

**Comment by mesqueeb** [comment]
these were released 🎉 
![image](https://user-images.githubusercontent.com/3253920/189252808-29dcb7b8-7033-479e-a827-79b9318b9c36.jpeg)
